spring:
  application:
    name: service-gateway    #服务名
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 16fd1108-bb19-44ef-aba5-a8811a74c4eb
      discovery:
        group: DEFAULT_GROUP
        server-addr: 127.0.0.1:8848
        namespace: 16fd1108-bb19-44ef-aba5-a8811a74c4eb
  config:
    import:
      - optional:nacos:service-gateway.yaml?group=DEFAULT_GROUP